sudo: required
language: android
jdk: oraclejdk8
android:
 components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-28
    - extra-android-m2repository
before_script:
 - chmod +x gradlew
 - yes | sdkmanager --licenses
script:
 - ./gradlew dependencies
 - ./gradlew build --stacktrace
