sudo: required
language: android
jdk: oraclejdk8

android:
 components:
    - platform-tools
    - tools
    - android-28
    - extra-android-m2repository

before_script:
 - chmod +x gradlew

before_install:
 - yes | sdkmanager "platforms;android-28"

script:
 - ./gradlew build --stacktrace