sudo: required
language: android
jdk: oraclejdk8
android:
 components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
 licenses:
    - android-sdk-license-.+
    - '.+'

before_script:
 - chmod +x gradlew

licenses:
 - android-sdk-license-.+
 - '.+'

before_install:
- yes | sdkmanager "platforms;android-28"

script:
 - ./gradlew dependencies
