language: android

branches:
  only:
    - master

android:
  components:
    - build-tools-28.0.3
    - android-28

script:
    - printf "user=$user\napikey=$apikey" > local.properties
    - echo "not execute"
    - ./gradlew install
    - ./gradlew # mytask